// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkrbthchzwjknatpupuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcmJ0aGNoendqa25hdHB1cHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzY3NjgsImV4cCI6MjA2MzYxMjc2OH0.pR0cI4EW5VZicJ2B3bPsqhNK9yQYB1K_WSweOOWH4rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);